[package]
name = "onchain_mtdt_sol"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
serde_json = "1.0.114"
syn = {version = "2.0.52",features = ['full']}

[[test]]
name = "mtdt_test"
path = "tests/mtdt_test.rs"